/*
 * Generated by MTK SP DrvGen Version 03.13.0 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Wed Nov 20 19:03:44 2013
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_MSDC1     GPIO_VMC
#define GPIO_DVDD28_MSDC2     GPIO_VIO18
#define GPIO_DVDD28_BPI     GPIO_VIO18


