/*
 * Generated by MTK SP DrvGen Version 03.13.0 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Wed Nov 20 19:03:44 2013
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


